/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {}
  interface AppRaces {}
  interface AppRoot {}
  interface AppStandings {}
  interface AppTabs {}
  interface ConstructorStandings {}
  interface DriverStandings {}
  interface NextRace {}
  interface RaceList {}
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRacesElement extends Components.AppRaces, HTMLStencilElement {}
  var HTMLAppRacesElement: {
    prototype: HTMLAppRacesElement;
    new (): HTMLAppRacesElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppStandingsElement extends Components.AppStandings, HTMLStencilElement {}
  var HTMLAppStandingsElement: {
    prototype: HTMLAppStandingsElement;
    new (): HTMLAppStandingsElement;
  };

  interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {}
  var HTMLAppTabsElement: {
    prototype: HTMLAppTabsElement;
    new (): HTMLAppTabsElement;
  };

  interface HTMLConstructorStandingsElement extends Components.ConstructorStandings, HTMLStencilElement {}
  var HTMLConstructorStandingsElement: {
    prototype: HTMLConstructorStandingsElement;
    new (): HTMLConstructorStandingsElement;
  };

  interface HTMLDriverStandingsElement extends Components.DriverStandings, HTMLStencilElement {}
  var HTMLDriverStandingsElement: {
    prototype: HTMLDriverStandingsElement;
    new (): HTMLDriverStandingsElement;
  };

  interface HTMLNextRaceElement extends Components.NextRace, HTMLStencilElement {}
  var HTMLNextRaceElement: {
    prototype: HTMLNextRaceElement;
    new (): HTMLNextRaceElement;
  };

  interface HTMLRaceListElement extends Components.RaceList, HTMLStencilElement {}
  var HTMLRaceListElement: {
    prototype: HTMLRaceListElement;
    new (): HTMLRaceListElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-races': HTMLAppRacesElement;
    'app-root': HTMLAppRootElement;
    'app-standings': HTMLAppStandingsElement;
    'app-tabs': HTMLAppTabsElement;
    'constructor-standings': HTMLConstructorStandingsElement;
    'driver-standings': HTMLDriverStandingsElement;
    'next-race': HTMLNextRaceElement;
    'race-list': HTMLRaceListElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {}
  interface AppRaces {}
  interface AppRoot {}
  interface AppStandings {}
  interface AppTabs {}
  interface ConstructorStandings {}
  interface DriverStandings {}
  interface NextRace {}
  interface RaceList {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-races': AppRaces;
    'app-root': AppRoot;
    'app-standings': AppStandings;
    'app-tabs': AppTabs;
    'constructor-standings': ConstructorStandings;
    'driver-standings': DriverStandings;
    'next-race': NextRace;
    'race-list': RaceList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-races': LocalJSX.AppRaces & JSXBase.HTMLAttributes<HTMLAppRacesElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'app-standings': LocalJSX.AppStandings & JSXBase.HTMLAttributes<HTMLAppStandingsElement>;
      'app-tabs': LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
      'constructor-standings': LocalJSX.ConstructorStandings & JSXBase.HTMLAttributes<HTMLConstructorStandingsElement>;
      'driver-standings': LocalJSX.DriverStandings & JSXBase.HTMLAttributes<HTMLDriverStandingsElement>;
      'next-race': LocalJSX.NextRace & JSXBase.HTMLAttributes<HTMLNextRaceElement>;
      'race-list': LocalJSX.RaceList & JSXBase.HTMLAttributes<HTMLRaceListElement>;
    }
  }
}


